### ISSUE TITLE
Support for LMS 5xx and merge with sicktoolbox2

### ISSUE THREAD

**Issue by bgromov** [ros-drivers/sicktoolbox#1]
Is there a chance to incorporate the changes from https://github.com/rhuitl/sicktoolbox which already supports LMS 5xx (with Ethernet connectivity)?

There is actually [a fork](https://github.com/rhuitl/laser_drivers) of `laser_drivers` that implements these changes via `sicktoolbox2` and `sicktoolbox_wrapper2` packages. Everything works perfectly, but it is not catkinized yet. So it would be great to merge official ROS version with that one.

**Comment by chadrockey** [comment]
The changes look too large to move into sicktoolbox (especially at this stage in the release cycle).

I would suggest making your own fork, catkinizing, and releasing from bloom (as sicktoolbox2).  I don't have access to test hardware, so I can't do it.
